tasks:
  - name: Gitpod Environment Custom
    command: |
      # Export from custom variables
      export EMAIL="$email" USER="$user" && \
      
      # Check again for make sure same
      echo "$EMAIL" "$USER" && \

      docker build --build-arg USER="$user" -t my_image

      yarn start

image:
  file: Dockerfile
